apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: europe-west1-docker.pkg.dev/helical-button-425403-t3/java-app/my-app1
        ports:
        - containerPort: 8080

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: java
spec:
  selector:
    app: java
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
