apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: europe-west1-docker.pkg.dev/helical-button-425403-t3/java-app/my-app1
        ports:
        - containerPort: 8080
